import 'package:equatable/equatable.dart';

abstract class PathSegment extends Equatable {
  bool matches(String concretePathSegment);

  @override
  bool? get stringify => true;

  /// Returns new variables generated by the PathSegment. Makes sense only if
  /// the PathSegment `matches` with the concretePathSegment.
  Map<String, String> getNewVariables(String concretePathSegment);
}
